### ISSUE TITLE
helm install issue "app.kubernetes.io/name" already defined

### ISSUE THREAD

**Issue by achovelon** [HEVAWEB/heva-helm-charts#3]
Hello,

I was previously also using the docker image and helm chart from this repo https://github.com/ssl-hep/hive-metastore/tree/main
And I found your chart. I tried to install a release using this spec 
```
`values:
    postgresql:
      enabled: false
    connections:
      database:
        database: hive
        host: pghost
    service:
      type: LoadBalancer
      port: 9083
    serviceAccount:
      create: false
    objectStore:
      endpoint: https://minio/
      accessKeyId: xxx
      secretAccessKey: xxx

```
But after many tried I always faced this error message 
`✗ HelmRelease reconciliation failed: Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 9: mapping key "app.kubernetes.io/name" already defined at line 7`

Do you have an example of working spec from your side ?
