### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by santurini** [HEVAWEB/heva-helm-charts#4]
I am using this `values.yaml` to deploy the metastore:
```
image:
  repository: sslhep/hive-metastore
  pullPolicy: IfNotPresent
  tag: "3.1.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: false
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}

securityContext:
  {}

service:
  type: ClusterIP
  port: 9083

ingress:
  enabled: false
  className: ""
  annotations:
    {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  {}

nodeSelector: {}

tolerations: []

affinity: {}

extraEnvVars: ""

extraEnvVarsSecret: ""

extraVolumeMounts: []

extraVolumes: []

connections:
  database:
    username: hive
    password: hive
    database: metastore
    host: "{{ .Release.Name }}-postgresql"
    port: 5432

conf:
  hiveSite:
    hive.metastore.warehouse.dir: "file:///tmp"
  hiveSiteSecret: ""
  hiveSiteSecretKey: "hivemetastore-site.xml"

objectStore:
  sslEnabled: true

  endpoint: "https://minio.mydomain.com"

  accessKeyId: "Dd4CEB4YysZpAIix2agh"

  secretAccessKey: "zrFOBjCxLLYazLrfNmZklWAigdStAKIkPynoJG9U"

  pathStyle: "true"

  impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"

log:
  level:
    meta: debug
    hive: info
    datanucleusorg: info
    datanucleus: info
    root: info

postgresql:
  enabled: true

  global:
    postgresql:
      auth:
        username: hive
        password: hive
        database: metastore

  primary:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce

    extendedConfiguration: |-
      password_encryption=md5

    service:
      ports:
        postgresql: "5432"
```

Then i install it like this: `helm install hive-metastore heva-helm-charts/hive-metastore -f hive-values.yaml -n hive`

And I get this error in the postgresql pod:
```
2025-02-05 11:59:25.636 GMT [1] LOG:  database system is ready to accept connections

2025-02-05 11:59:43.200 GMT [112] FATAL:  password authentication failed for user "hive"

2025-02-05 11:59:43.200 GMT [112] DETAIL:  Password does not match for user "hive".

	Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 1: "host     all             all             0.0.0.0/0               md5"

2025-02-05 11:59:44.254 GMT [113] FATAL:  password authentication failed for user "hive"
```

And this error in the metastore pod:
```
02/05/25 12:06:18 INFO org.apache.hadoop.hive.metastore.HiveMetaStore: Starting hive metastore on port 9083

02/05/25 12:06:18 INFO org.apache.hadoop.hive.metastore.HiveMetaStore: 0: Opening raw store with implementation class:org.apache.hadoop.hive.metastore.ObjectStore

02/05/25 12:06:18 WARN org.apache.hadoop.hive.metastore.ObjectStore: datanucleus.autoStartMechanismMode is set to unsupported value null . Setting it to value: ignored

02/05/25 12:06:18 INFO org.apache.hadoop.hive.metastore.ObjectStore: ObjectStore, initialize called

02/05/25 12:06:18 INFO org.apache.hadoop.hive.metastore.conf.MetastoreConf: Unable to find config file hivemetastore-site.xml

02/05/25 12:06:18 INFO org.apache.hadoop.hive.metastore.conf.MetastoreConf: Found configuration file null

02/05/25 12:06:18 INFO org.apache.hadoop.hive.metastore.conf.MetastoreConf: Unable to find config file metastore-site.xml

02/05/25 12:06:18 INFO org.apache.hadoop.hive.metastore.conf.MetastoreConf: Found configuration file null

02/05/25 12:06:18 INFO DataNucleus.Persistence: Property datanucleus.cache.level2 unknown - will be ignored

02/05/25 12:06:18 INFO com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Starting...

02/05/25 12:06:19 ERROR com.zaxxer.hikari.pool.HikariPool: HikariPool-1 - Exception during pool initialization.

org.postgresql.util.PSQLException: FATAL: password authentication failed for user "hive"
```
